Lecture 1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name='wiki'

urlpatterns = [
    path("", views.index, name="index"),
    path('wiki/<str:title>', views.wiki_entry, name='wiki_entry'),
    path("search_/", views.search_, name="search_"),
    path('newpage/', views.newpage, name='newpage'),
    path('wiki/<str:title>/edit', views.editpage, name='editpage'),
    path('ramdom/', views.randompage, name='randompage')
]

Lecture 1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls", namespace='encyclopedia'))
]

Lecture 1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

Lecture 1/wiki/encyclopedia/views.py
from django.shortcuts import redirect, render
from . import util
import markdown, random
from django import forms



class NewPageForm(forms.Form):
        title = forms.CharField(
        label='Title', max_length=100, min_length=1, 
        widget=forms.TextInput(attrs={'class': 'my-title-area', 'placeholder': 'Enter a title:'}))
        
        content = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'my-text-area', 'placeholder': 'Enter the content:'}),
        label ='Content', min_length=1,
        )
        
class EditPageForm(forms.Form):
        title = forms.CharField(
        label='Title', max_length=100, min_length=1,
        widget=forms.TextInput(attrs={'placeholder': 'Enter a title:'}))

        content = forms.CharField(
        label='Content', min_length=1,
        widget=forms.Textarea(attrs={'class': 'my-text-area', 'placeholder': 'Enter the content:'}),
        )


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def md_to_html(title):
    content = util.get_entry(title)
    markdownder = markdown.Markdown()
    if content == None:
        return None
    else:
        return markdownder.convert(content)
    
def wiki_entry(request, title):
    html_topic = md_to_html(title)
    if html_topic == None:
       return render(request, "encyclopedia/error.html", {"error_message": "We could not find the above page on our servers."})
    else:
        return render(request, "encyclopedia/entry.html", {
        "content": html_topic, 
         "title": title
        } )



def search_(request):
    if request.method == "GET":
        search = request.GET['q']
        html_topic = md_to_html(search)
        if html_topic is not None:
            return render(request, "encyclopedia/entry.html", {
                "content": html_topic, 
                "title": search
            })
        else:
            allEntries = util.list_entries()
            recommend = []
            for entry in allEntries:
                if search.lower() in entry.lower():
                    recommend.append(entry)
            if len(recommend) == 0:
                
                
                return render(request, "encyclopedia/search_error.html", {
                    
                    "new_page_link": search
                })
                
            else:
                return render(request, "encyclopedia/search.html", {
                    "recommend": recommend
                })


def newpage(request):
    
    if request.method == 'POST':
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            content_with_title = f'# {title}\n\n{content}'
            if title in util.list_entries():
                 return render(request, "encyclopedia/error.html", {
                    "error_message": f"An entry with the title '{title}' already exists.",
                    "title_link": title
                })
            util.save_entry(title, content_with_title)
            return render(request, "encyclopedia/entry.html", {
                "content": md_to_html(title), 
                "title": title

            })
    else:
        form = NewPageForm()
    return render(request, 'encyclopedia/newpage.html', {'form': form})
               
    
def editpage(request, title):
    if request.method == 'POST':
        form = EditPageForm(request.POST)
        if form.is_valid():
            new_content = form.cleaned_data['content']
            util.save_entry(title, new_content)
            return redirect('wiki:wiki_entry', title=title)
    else:
        content = util.get_entry(title)
        if content is None:
            return render(request, "encyclopedia/error.html", {"error_message": "We could not find the above page on our servers."})
        else:
            form = EditPageForm(initial={'title': title, 'content': content})
        return render(request, 'encyclopedia/editpage.html', {'form': form, 'title': title})

def randompage(request):
    allEntries = util.list_entries()
    randomEntry = random.choice(allEntries)
    return redirect('wiki:wiki_entry', title=randomEntry)

Lecture 1/wiki/encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit Page - {{ form.title.value }}
{% endblock %}

{% block body %}
<h1>Edit Page</h1>
<hr>
<hr>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>

{% endblock %}

Lecture 1/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <p>{{ content | safe }}</p>
    <a href="{% url 'wiki:editpage' title %}" class="btn btn-outline-primary">Edit</a>
{% endblock %}

Lecture 1/wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Error
{% endblock %}

{% block body %}

{% if error_message %}
<div class="alert alert-danger" role="alert">
    
    {{ error_message }} {% if title_link %}
        <a href="{% url 'wiki:wiki_entry' title_link %}">Click here</a> to view the existing page.
    {% endif %}


</div>
{% endif %}

{% endblock %}

Lecture 1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>


        <ul class="list-group list-group-flush" style="margin-top: 45px;">
            {% for entry in entries %}
                <li class="list-group-item" style="margin-top: 2px;"><a href="{% url 'wiki:wiki_entry' title=entry%}" >{{ entry }}</a></li>
            {% endfor %}
        </ul>
{% endblock %}

Lecture 1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
       <link rel="stylesheet" href="{% static 'encyclopedia/styles.css' %}">
        <link rel="shortcut icon" href="https://cdn.icon-icons.com/icons2/622/PNG/512/wikipedia-logo_icon-icons.com_57053.png" type="image/x-icon">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">

                <a id='wiki-title-index' href="{% url 'wiki:index'%}">
                    <h2>Wiki</h2>
                </a>
                
                <form action="{% url 'wiki:search_' %}" method="GET" > 
                   
                     
                 <div class="input-group mb-3">
                    <input type="text" class="form-control" name="q" placeholder="Search Encyclopedia" aria-label="Search Encyclopedia" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="search_button" type="submit">Search</button>
                        </div>
                 </div>
                    
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:randompage'%}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                
                {% endblock %}
            </div>
        </div>


    </body>
</html>

Lecture 1/wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
 New Article
{% endblock %}

{% block body %}
    <h1>New Page</h1> 
    <hr>
    <hr>
    <h4>Thank you for your interest in contributing to our Encyclopedia!</h4>
    <br>
    
    

    <form method="POST">
      {% csrf_token %}

      {{ form.as_p }}
      
      <button type="submit" class="btn btn-primary" data-bs-toggle="button">Save</button>
    </form>


{% endblock %}
    

Lecture 1/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  {{title}}
{% endblock %}

{% block body %}
    <h1>Search</h1>

    <ul>
        {% for entry in recommend %}
            <li><a href="{% url 'wiki:wiki_entry' title=entry%}" >{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

Lecture 1/wiki/encyclopedia/templates/encyclopedia/search_error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Not Found
{% endblock %}

{% block body %}


<div>
    <h1>Search Results</h1>
    <hr>
    <hr>
</div>

<div class="alert alert-danger" role="alert">
    <p>The requested page was not found.</p>
</div>

<p>
    <em>The page <strong>"{{ new_page_link }}"</strong> does not exist. <a href="{% url 'wiki:newpage'%}">You can create one by clicking here</a></em>
</p>




{% endblock %}